version: '3.1'

services:
  mongo:
    image: mongo:4
    restart: always
    ports:
      - 27017:27017 # Your service will use this
    volumes:
      - ~/data/why:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
